# Dependabot
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates

version: 2.0
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: pre-commit
    directory: /
    schedule:
      interval: daily
    groups:
      pre-commit:
        patterns:
          - "*"
