name: Dependabot Approve and Merge

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  dependabot:
    name: Dependabot
    uses: ./.github/workflows/dependabot.yml
    secrets:
      pr_approve_and_merge_pem: ${{ secrets.PR_APPROVE_AND_MERGE_PEM }}
