name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  id-token: write

jobs:
  release:
    name: Release
    uses: osinfra-io/pt-techne-misc-workflows/.github/workflows/release.yml@7ed8c49dde7d72864db8b10423592c85fc30df80  # v0.2.3
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
