name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  id-token: write

jobs:
  release:
    name: Release
    uses: osinfra-io/pt-techne-misc-workflows/.github/workflows/release.yml@3f58f13c9ff1c2c4a94cecad4bab5d3e78d69bce  # v0.2.2
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
