name: Nuclei Vulnerability Scan Called Workflow

on:
  workflow_call:
    inputs:
      urls_file:
        description: "Path to the file containing URLs to scan with Nuclei"
        required: true
        type: string

permissions:
  security-events: write

jobs:
  nuclei-scan:
    name: Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      # GitHub Checkout
      # https://github.com/marketplace/actions/checkout

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      # Nuclei
      # https://github.com/projectdiscovery/nuclei-action

      - name: Nuclei run
        id: nuclei_scan
        uses: projectdiscovery/nuclei-action@32a91c0da7be14c07b0ade6c14fa0f6e78d97c9c  # v3.1.0
        with:
          args: "-list ${{ inputs.urls_file }} -severity low,medium,high,critical -H 'User-Agent: osinfra.io - Vulnerability Scan' -sarif-export nuclei.sarif"

      # GitHub Upload Artifact
      # https://github.com/actions/upload-artifact

      - name: GitHub workflow artifacts
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f  # v7.0.0
        with:
          name: nuclei-artifacts
          path: |
            nuclei.sarif

      # GitHub CodeQL upload SARIF
      # https://github.com/github/codeql-action

      - name: GitHub security dashboard alerts update
        uses: github/codeql-action/upload-sarif@c10b8064de6f491fea524254123dbe5e09572f13  # v4.35.1
        if: success() && hashFiles('nuclei.sarif') != ''
        with:
          sarif_file: nuclei.sarif
          category: Nuclei
